### PR TITLE
 Rework styling in layout.css, separate from smartpanel.css

### PR DESCRIPTION
**Pull request by jw35**
This pull-request represents an experiment. I believe the result is worthwhile, but may have implications that I haven't thought of. Comments, even negative ones, would be welcome.

This version of tfc_web is currently running on 
tfc-app4, in particular serving http://tfc-app4.cl.cam.ac.uk/smartpanel/layout/1/

Change summary:

Seperate layout.html from layout_config.html. Initailly by 
making it depend on a seperate css file, layout.css, which started as a
copy of smartpanel.css.

In layout.html, switch the grid layout to using nested \<div\>s rather
then \<ol\>/\<li\> and limit in-line CSS to things we want to template
effecting size and/or position. Arrange that it has fewer implications
for the styling of the widgets themselves, remove global suppression of
margin/border, etc. Add 'class="layout"' to the body tag.

In layout.css, adapt styling copied over from smartpanel.css to match
the changes above and remove unreferenced rules ans unnecessary styling.
USe absolute positioning to locate the logo and grid container divs to
avoid the need to globally set margins and padding to 0. All layout.css
selectors are prefixed by .layout. This essentially namespace-
qualifies all the class names to make it easier to use layout.css
with other css without name clashes.

In widgets.css, remove the rules that were only there to undo changes
applied by smartpanel.css, and move the global reset of box-model
styling into layout.css where it belongs.

### CODE REVIEW

**Comment by abrahammartin** [comment]
I'm working on a new layout designer so I'll leave this pending until we have it

**Comment by jw35** [comment]
Closes #108

**Comment by abrahammartin** [comment]
outdated with the new designer

**Comment by abrahammartin** [comment]
@jw35 do you want to adapt this PR to the new designer or should I close it?

**Comment by jw35** [comment]
I don't think it's wort re-doing it. It was intended to make it possible to simplify the CSS needed so that various widgets displayed correctly, but we have workarounds in place (even if they are messy) so there's no immediate need.

I'll close this PR and delete the corresponding branch (though I might keep a copy myself...)

**Pull request closed without merging**
